name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true
          go-package: ./...
          fail-on-error: true

      - name: Run gostyle
        uses: k1LoW/gostyle-action@v1
        with:
          fail-on-error: true

      - name: Run tests
        run: make ci

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
